Update

diff --git a/dot_local/bin/executable_theme-switch b/dot_local/bin/executable_theme-switch
--- a/dot_local/bin/executable_theme-switch
+++ b/dot_local/bin/executable_theme-switch
@@ -1,51 +1,106 @@
 #!/usr/bin/env fish
 
-function fail_usage
-    echo "Usage: theme-switch [light|dark]"
+function print_usage
+    echo "Usage: theme-switch [-d|-h|light|dark]"
+    echo -e "\t-d\tDaemonise"
+    echo -e "\tlight\tOne-time switch to light mode"
+    echo -e "\tdark\tOne-time switch to dark mode"
     exit 1
 end
 
-set -l force_mode ""
+set force_mode ""
+set daemonise 0
+set ignore_diff 0
+
 switch (count $argv)
     case 0
         : # do nothing
     case 1
-        set force_mode $argv[1]
-        if ! string match -r "^light|dark\$" -- "$force_mode"
-            fail_usage
+        switch $argv[1]
+            case light
+                set force_mode light
+            case dark
+                set force_mode dark
+            case -d
+                set daemonise 1
+            case -h
+                print_usage
+                exit 0
         end
+        # set force_mode $argv[1]
+        # if ! string match -r "^light|dark\$" -- "$force_mode"
+        #     fail_usage
+        # end
     case '*'
-        fail_usage
+        print_usage
+        exit 1
 end
 
-set -l current_hour (date +%k)
-set -l current_gsettings_mode (/usr/bin/gsettings get org.gnome.desktop.interface color-scheme | string match -gr "'prefer-(light|dark)'")
-echo "Current hour is $current_hour" >&2
-echo "Current mode is $current_gsettings_mode" >&2
+set main_old_status ""
+function main
 
-set -l to_set_mode ""
-if test \( -z $force_mode -a $current_hour -ge 8 -a $current_hour -lt 19 \) -o $force_mode = light
-    set to_set_mode light
+    set -l current_hour (date +%k)
+    set -l current_gsettings_mode (/usr/bin/gsettings get org.gnome.desktop.interface color-scheme | string match -gr "'prefer-(light|dark)'")
+
+    echo "Current hour is $current_hour" >&2
+    echo "Current mode is $current_gsettings_mode" >&2
+
+    set -l current_daylight_status ""
+    if test \( $current_hour -ge 8 -a $current_hour -lt 20 \)
+        set current_daylight_status light
+    else
+        set current_daylight_status dark
+    end
+
+    set -l to_set_mode ""
+    if test -n $force_mode
+        set to_set_mode $force_mode
+    else
+        set to_set_mode $current_daylight_status
+    end
+
+    if test \( $current_daylight_status != $main_old_status -a -z $force_mode \)
+        set ignore_diff 0
+    end
+
+    if test \( $daemonise -eq 1 -a $to_set_mode != $current_gsettings_mode -a $ignore_diff -eq 1 \)
+        echo "Nothing to do. Theme was manually overridden. Maintaining override until change of daylight cycle."
+        return 0
+    end
+
+    set ignore_diff 1
+    set main_old_status $current_daylight_status
+
+    if test $to_set_mode = $current_gsettings_mode
+        echo "Nothing to do. Already $current_gsettings_mode"
+        return 0
+    end
+
+    if test $to_set_mode = light
+        set theme_type light
+        set gsettings_prefer prefer-light
+        set qt_theme org.kde.breeze.desktop
+    else
+        set theme_type dark
+        set gsettings_prefer prefer-dark
+        set qt_theme org.kde.breezedark.desktop
+    end
+    echo "Set theme to $theme_type" >&2
+
+    if niri msg version &>/dev/null
+        niri msg action do-screen-transition
+    end
+
+    /usr/bin/gsettings set org.gnome.desktop.interface color-scheme \'$gsettings_prefer\'
+    /usr/bin/lookandfeeltool -a $qt_theme
+    notify-send --urgency=low --expire-time=1500 "Switched to $theme_type mode!"
+end
+
+if test $daemonise -eq 1
+    while true
+        main
+        sleep 5
+    end
 else
-    set to_set_mode dark
+    main
 end
-
-if test $to_set_mode = $current_gsettings_mode
-    echo "Nothing to do. Already $current_gsettings_mode"
-    exit 0
-end
-
-if test $to_set_mode = light
-    set theme_type light
-    set gsettings_prefer prefer-light
-    set qt_theme org.kde.breeze.desktop
-else
-    set theme_type dark
-    set gsettings_prefer prefer-dark
-    set qt_theme org.kde.breezedark.desktop
-end
-echo "Set theme to $theme_type" >&2
-
-/usr/bin/gsettings set org.gnome.desktop.interface color-scheme \'$gsettings_prefer\'
-/usr/bin/lookandfeeltool -a $qt_theme
-notify-send --urgency=low --expire-time=1500 "Switched to $theme_type mode!"
